# PyTorch: Basic operations


In [2]:
# Import PyTorch library
import torch

In [36]:
# Empty tensor (uninitialized values)
torch.empty(2, 3)

# Tensor filled with zeros
torch.zeros(2,3,4)

# Tensor filled with ones
torch.ones(2, 3)

# Tensor from list
torch.tensor([[1, 2, 3], [4, 5, 6]])

# Tensor with a specific value
torch.full((2, 3), 3)

# Identity matrix
torch.eye(4)

# Random
torch.randn(3, 3)


tensor([[-1.0571,  0.9950,  1.9032],
        [ 2.0355,  1.5587, -0.2035],
        [ 1.6297, -0.3699, -0.1257]])

In [40]:
# Basic arithmetic operations
x = torch.tensor([10, 20, 30], dtype=torch.float32)
y = torch.tensor([1, 2, 3], dtype=torch.float32)

# Addition
x + y

# Subtraction
x - y

# Multiplication
x * y

# Division
x / y


tensor([10., 10., 10.])

In [53]:
# Create a 3x2 tensor with random values sampled from a standard normal distribution
x = torch.randn(3, 2)

# Print the original tensor
print(x)

# Print the sum of all elements in the tensor (scalar)
x.sum()

# Print the sum of elements along rows (resulting in a 1D tensor of column sums)
x.sum(dim=0)

# Print the mean (average) of all elements in the tensor (scalar)
x.mean()

# Print the mean of elements along rows (1D tensor of column means)
x.mean(dim=1)

# Reshape the tensor to a 1D tensor with 6 elements (flatten)
x.view(1, 6, 1, 1, 1)

# Reshape the tensor to a 2x3 tensor; -1 lets PyTorch infer the correct dimension
x.view(3, -1)


tensor([[-0.1953, -0.4289],
        [ 1.2690, -0.2622],
        [ 0.4880, -0.3044]])


tensor([[-0.1953, -0.4289],
        [ 1.2690, -0.2622],
        [ 0.4880, -0.3044]])

In [55]:
import numpy as np

# Create a NumPy array
np_array = np.array([[1, 2, 3], [4, 5, 6]])

# Convert the NumPy array to a PyTorch tensor
# The tensor will share memory with the NumPy array (changing one will affect the other,
# if they're of compatible types).
tensor_convert = torch.from_numpy(np_array)


In [ ]:
# Convert the PyTorch tensor back to a NumPy array
# detach() is used to ensure the tensor is not part of the computation graph,
# cpu() is used to move the tensor to CPU memory if it's on a GPU.
# numpy() converts the tensor to a NumPy array.

tensor_convert.detach().cpu().numpy()


array([[1, 2, 3],
       [4, 5, 6]])