# PyTorch: Autograd

`torch.autograd` is PyTorch’s automatic differentiation engine. It tracks all operations on tensors to build a “computational graph”, and allows you to automatically compute gradients for optimization (used in training neural networks).


In [2]:
import torch

### Simple example


In [3]:
# Create a tensor and enable gradient tracking
x = torch.tensor(2.0, requires_grad=True)

# Perform some operations
y = x**2 + 3*x + 1
print(y)

# Compute the gradient of y with respect to x
y.backward()

print(x.grad)

tensor(11., grad_fn=<AddBackward0>)
tensor(7.)


In [4]:
# Convert the tensor to a NumPy array
x.detach().numpy()

array(2., dtype=float32)

#### 🔗 Visualization of the Computation Graph

Here's a simple ASCII illustration:

```
      x
      |
     [**2]
      |
     y1 = x**2
      |
    [+] <-----------+
      |             |
   [3 * x]      [+ 1]
      |             |
      +-------------+
             |
             y
```


### Another example


In [7]:
# Create tensors with requires_grad=True to track computation
a = torch.tensor([5.0], requires_grad=True)
b = torch.tensor([6.0], requires_grad=True)

# Define a function of a and b
y = a**3 - b**2 + 3

# Perform backpropagation to compute gradients
y.backward()

# Print the gradients
print(a.grad)
print(b.grad)

tensor([75.])
tensor([-12.])


### Multi-dimensional example


In [6]:
w = torch.randn(2, 2, requires_grad=True)
b = torch.randn(2, requires_grad=True)
input = torch.randn(2, 2)

output = (w * input).sum() + b.sum()
output.backward()

print(w.grad)
print(b.grad)

tensor([[-0.0873, -0.6040],
        [-0.1075, -0.1958]])
tensor([1., 1.])
