In [1]:
from pprint import pp

In [2]:
import torch
import torch.nn.functional as F
from sklearn.metrics import classification_report


def calc_metrices(logits: torch.Tensor, labels: torch.Tensor, isPrint=False):
    # Apply softmax to logits to obtain prediction probabilities for each class
    probs = F.softmax(logits, dim=1)  # Shape: (batch_size, num_classes)
    
    # Use argmax to get the predicted class index for each sample
    preds = torch.argmax(probs, dim=1)  # Shape: (batch_size)

    # Move prediction and label tensors to CPU and convert to numpy arrays for scikit-learn compatibility
    preds_np = preds.cpu().numpy()
    labels_np = labels.cpu().numpy()

    # Generate the classification report as a dictionary (includes precision, recall, f1, etc.)
    report = classification_report(labels_np, preds_np, output_dict=True)

    # Optionally print a nicely formatted classification report if isPrint is True
    if isPrint:
        print(classification_report(labels_np, preds_np, digits=3))
    
    # Return the report dictionary and the numpy arrays of predictions and labels
    return report, preds_np, labels_np

In [3]:
# Example usage:

batch_size = 20
num_classes = 5
logits = torch.randn(batch_size, num_classes)  # Example random logits
labels = torch.randint(0, num_classes, (batch_size,))  # Example random true labels
pp(logits)
pp(labels)

tensor([[-0.4925, -1.0501,  0.7374, -0.6831,  0.5468],
        [ 0.5041, -0.1952,  0.6149,  1.4452, -1.7081],
        [-1.8173,  0.0104, -0.7647, -0.4262,  1.0061],
        [-0.1947, -1.6813, -1.5153,  1.5417, -0.3853],
        [-0.8865,  0.5450, -3.2425,  0.9044, -0.7813],
        [-1.4866,  0.5388, -1.9052, -0.0077, -0.0574],
        [ 0.0997, -1.3931, -1.0418,  0.4103, -0.1669],
        [-0.6091, -0.2481, -1.8405, -0.2603, -0.6629],
        [ 0.9757, -0.2948, -0.9275,  0.6750,  0.7674],
        [-1.2540,  1.4025, -0.6275,  0.7125,  0.7643],
        [ 0.2539, -0.5859, -1.4482,  0.2277, -0.6533],
        [ 0.2215,  1.2965,  0.0377, -0.7398,  0.5624],
        [-1.2013,  1.2570,  0.6958, -0.3266,  0.0103],
        [-0.5863,  0.2126, -0.4212, -0.5918,  0.5015],
        [-0.5952,  0.0499,  0.4888,  1.5249,  0.1289],
        [-0.0306, -0.3177, -0.7104,  0.8835,  1.8006],
        [ 1.5423,  0.5960,  2.3458,  0.7902,  0.3960],
        [ 1.2602, -0.1882, -1.5202, -1.7464, -0.4479],
        [ 

In [4]:
report, pred, labels = calc_metrices(logits, labels, isPrint=True)


              precision    recall  f1-score   support

           0      0.000     0.000     0.000         4
           1      0.200     0.250     0.222         4
           2      0.000     0.000     0.000         3
           3      0.167     0.250     0.200         4
           4      0.250     0.200     0.222         5

    accuracy                          0.150        20
   macro avg      0.123     0.140     0.129        20
weighted avg      0.136     0.150     0.140        20



In [5]:
pp(report)
pp(pred)
pp(labels)

{'0': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 4.0},
 '1': {'precision': 0.2,
       'recall': 0.25,
       'f1-score': 0.2222222222222222,
       'support': 4.0},
 '2': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0},
 '3': {'precision': 0.16666666666666666,
       'recall': 0.25,
       'f1-score': 0.2,
       'support': 4.0},
 '4': {'precision': 0.25,
       'recall': 0.2,
       'f1-score': 0.2222222222222222,
       'support': 5.0},
 'accuracy': 0.15,
 'macro avg': {'precision': 0.12333333333333334,
               'recall': 0.13999999999999999,
               'f1-score': 0.1288888888888889,
               'support': 20.0},
 'weighted avg': {'precision': 0.13583333333333333,
                  'recall': 0.15,
                  'f1-score': 0.13999999999999999,
                  'support': 20.0}}
array([2, 3, 4, 3, 3, 1, 3, 1, 0, 1, 0, 1, 1, 4, 3, 4, 2, 0, 4, 3])
array([1, 4, 1, 3, 0, 2, 2, 1, 4, 0, 3, 4, 0, 0, 2, 3, 3, 1, 4, 4])
